---
galaxy_info:
  author: James HORLEY
  description: Bootstrap server
  license: license GPLv2
  min_ansible_version: 1.2

  platforms:
  - name: CentOS
    versions:
    - 6

  categories:
  - system

dependencies: []

