---
- name: application de la configuration de base
  hosts: all

  vars:
    - admin_email: admin@education.pf
    - install_phpmyadmin: yes
    - name_sysdeploy: sysadmin

  roles:
    - { role: common, tags: ['bootstrap'] }
    - { role: webserver, tags: ['webserver'] }


